/*
 * MATLAB Compiler: 4.0 (R14)
 * Date: Thu Apr 20 17:12:05 2006
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe"
 * "launcher.m" "co_occ_features.m" "main_loop.dll" "main_loop_b.dll"
 * "oc_matrix1a.dll" "oc_matrix2a.dll" "oc_matrix3a.dll" "oc_matrix_ver2.dll"
 * "feature_1.dll" "feature_2.dll" "feature_3.dll" "feature_4.dll"
 * "feature_5.dll" "oc_matrixb.dll" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_launcher_public_data[] = {'3', '0', '8', '1', '9',
                                                    'D', '3', '0', '0', 'D',
                                                    '0', '6', '0', '9', '2',
                                                    'A', '8', '6', '4', '8',
                                                    '8', '6', 'F', '7', '0',
                                                    'D', '0', '1', '0', '1',
                                                    '0', '1', '0', '5', '0',
                                                    '0', '0', '3', '8', '1',
                                                    '8', 'B', '0', '0', '3',
                                                    '0', '8', '1', '8', '7',
                                                    '0', '2', '8', '1', '8',
                                                    '1', '0', '0', 'C', '4',
                                                    '9', 'C', 'A', 'C', '3',
                                                    '4', 'E', 'D', '1', '3',
                                                    'A', '5', '2', '0', '6',
                                                    '5', '8', 'F', '6', 'F',
                                                    '8', 'E', '0', '1', '3',
                                                    '8', 'C', '4', '3', '1',
                                                    '5', 'B', '4', '3', '1',
                                                    '5', '2', '7', '7', 'E',
                                                    'D', '3', 'F', '7', 'D',
                                                    'A', 'E', '5', '3', '0',
                                                    '9', '9', 'D', 'B', '0',
                                                    '8', 'E', 'E', '5', '8',
                                                    '9', 'F', '8', '0', '4',
                                                    'D', '4', 'B', '9', '8',
                                                    '1', '3', '2', '6', 'A',
                                                    '5', '2', 'C', 'C', 'E',
                                                    '4', '3', '8', '2', 'E',
                                                    '9', 'F', '2', 'B', '4',
                                                    'D', '0', '8', '5', 'E',
                                                    'B', '9', '5', '0', 'C',
                                                    '7', 'A', 'B', '1', '2',
                                                    'E', 'D', 'E', '2', 'D',
                                                    '4', '1', '2', '9', '7',
                                                    '8', '2', '0', 'E', '6',
                                                    '3', '7', '7', 'A', '5',
                                                    'F', 'E', 'B', '5', '6',
                                                    '8', '9', 'D', '4', 'E',
                                                    '6', '0', '3', '2', 'F',
                                                    '6', '0', 'C', '4', '3',
                                                    '0', '7', '4', 'A', '0',
                                                    '4', 'C', '2', '6', 'A',
                                                    'B', '7', '2', 'F', '5',
                                                    '4', 'B', '5', '1', 'B',
                                                    'B', '4', '6', '0', '5',
                                                    '7', '8', '7', '8', '5',
                                                    'B', '1', '9', '9', '0',
                                                    '1', '4', '3', '1', '4',
                                                    'A', '6', '5', 'F', '0',
                                                    '9', '0', 'B', '6', '1',
                                                    'F', 'C', '2', '0', '1',
                                                    '6', '9', '4', '5', '3',
                                                    'B', '5', '8', 'F', 'C',
                                                    '8', 'B', 'A', '4', '3',
                                                    'E', '6', '7', '7', '6',
                                                    'E', 'B', '7', 'E', 'C',
                                                    'D', '3', '1', '7', '8',
                                                    'B', '5', '6', 'A', 'B',
                                                    '0', 'F', 'A', '0', '6',
                                                    'D', 'D', '6', '4', '9',
                                                    '6', '7', 'C', 'B', '1',
                                                    '4', '9', 'E', '5', '0',
                                                    '2', '0', '1', '1', '1'
                                                    , '\0'};

const char *__MCC_launcher_name_data = "launcher";

const char *__MCC_launcher_root_data = "";

const unsigned char __MCC_launcher_session_data[] = {'B', 'F', '6', 'A', '5',
                                                     'F', 'F', 'D', '9', 'D',
                                                     '3', '5', 'D', 'B', 'C',
                                                     '6', 'D', 'D', 'F', '0',
                                                     'B', '5', '9', 'F', '7',
                                                     '2', '5', '0', 'C', 'C',
                                                     '3', '5', '8', '8', 'F',
                                                     '9', '2', '6', '2', '8',
                                                     '8', 'E', 'B', '3', '3',
                                                     '6', 'C', 'C', '0', '3',
                                                     'C', 'C', 'C', 'D', '8',
                                                     '2', '2', '0', '3', '9',
                                                     '1', '2', 'E', 'A', '4',
                                                     '4', 'D', 'C', 'B', 'C',
                                                     'E', 'D', '4', '1', '9',
                                                     '3', 'D', '5', 'F', '0',
                                                     '1', '5', 'B', 'A', 'E',
                                                     '4', '3', '0', '5', '5',
                                                     '9', 'D', 'B', 'E', '9',
                                                     '5', '2', 'F', 'B', '3',
                                                     'F', '6', 'D', 'E', '0',
                                                     '9', 'C', 'A', '2', '0',
                                                     '6', '5', '7', '0', '5',
                                                     '3', '3', '6', 'C', 'C',
                                                     '8', '9', '3', '7', '1',
                                                     'F', 'D', '8', 'E', '4',
                                                     'A', 'E', 'B', 'B', '3',
                                                     'E', '8', 'A', 'D', '8',
                                                     'A', '9', 'B', '1', '7',
                                                     'B', '3', '3', 'D', 'C',
                                                     '3', '5', '1', 'E', '5',
                                                     '1', '8', 'F', '2', '5',
                                                     'F', '3', 'E', '1', 'F',
                                                     '9', 'C', '2', '0', '0',
                                                     'E', '6', 'A', '0', 'F',
                                                     'C', '8', '7', '6', 'B',
                                                     '3', 'A', '3', 'D', 'A',
                                                     'D', '3', 'C', '9', '4',
                                                     '9', '1', 'F', 'B', '0',
                                                     '6', '2', '8', 'A', 'D',
                                                     '0', 'D', '3', '6', 'A',
                                                     '4', '0', 'E', 'C', 'F',
                                                     '5', 'B', '6', 'E', '1',
                                                     '2', '8', 'F', 'D', 'B',
                                                     '7', '4', 'C', '4', '5',
                                                     '1', '5', 'C', '9', 'B',
                                                     '8', '9', 'A', '1', 'F',
                                                     'E', '0', 'A', '1', '5',
                                                     '5', '0', 'E', '5', 'D',
                                                     'F', '1', '3', '7', '6',
                                                     'F', '1', 'B', '1', '8',
                                                     'D', '\0'};

const char *__MCC_launcher_matlabpath_data[] = {"launcher/",
                                                "work/co-occ-features/",
                                                "toolbox/compiler/deploy/",
                                                "work/co-occ-features/dll files/",
                                                "$TOOLBOXMATLABDIR/general/",
                                                "$TOOLBOXMATLABDIR/ops/",
                                                "$TOOLBOXMATLABDIR/lang/",
                                                "$TOOLBOXMATLABDIR/elmat/",
                                                "$TOOLBOXMATLABDIR/elfun/",
                                                "$TOOLBOXMATLABDIR/specfun/",
                                                "$TOOLBOXMATLABDIR/matfun/",
                                                "$TOOLBOXMATLABDIR/datafun/",
                                                "$TOOLBOXMATLABDIR/polyfun/",
                                                "$TOOLBOXMATLABDIR/funfun/",
                                                "$TOOLBOXMATLABDIR/sparfun/",
                                                "$TOOLBOXMATLABDIR/scribe/",
                                                "$TOOLBOXMATLABDIR/graph2d/",
                                                "$TOOLBOXMATLABDIR/graph3d/",
                                                "$TOOLBOXMATLABDIR/specgraph/",
                                                "$TOOLBOXMATLABDIR/graphics/",
                                                "$TOOLBOXMATLABDIR/uitools/",
                                                "$TOOLBOXMATLABDIR/strfun/",
                                                "$TOOLBOXMATLABDIR/imagesci/",
                                                "$TOOLBOXMATLABDIR/iofun/",
                                                "$TOOLBOXMATLABDIR/audiovideo/",
                                                "$TOOLBOXMATLABDIR/timefun/",
                                                "$TOOLBOXMATLABDIR/datatypes/",
                                                "$TOOLBOXMATLABDIR/verctrl/",
                                                "$TOOLBOXMATLABDIR/codetools/",
                                                "$TOOLBOXMATLABDIR/helptools/",
                                                "$TOOLBOXMATLABDIR/winfun/",
                                                "$TOOLBOXMATLABDIR/demos/",
                                                "toolbox/local/",
                                                "toolbox/stateflow/stateflow/",
                                                "toolbox/shared/hds/",
                                                "toolbox/compiler/",
                                                "toolbox/control/control/",
                                                "toolbox/control/ctrlguis/",
                                                "toolbox/control/ctrlobsolete/",
                                                "toolbox/control/ctrlutil/",
                                                "toolbox/shared/controllib/",
                                                "toolbox/shared/optimlib/",
                                                "toolbox/database/database/",
                                                "toolbox/mbc/mbc/",
                                                "toolbox/nnet/nnet/",
                                                "toolbox/nnet/nnutils/",
                                                "toolbox/optim/",
                                                "toolbox/signal/signal/",
                                                "toolbox/signal/sigtools/",
                                                "toolbox/symbolic/"};
const int __MCC_launcher_matlabpath_data_count = 50;

const char *__MCC_launcher_mcr_application_options[] = { "" };
const int __MCC_launcher_mcr_application_option_count = 0;
const char *__MCC_launcher_mcr_runtime_options[] = { "" };
const int __MCC_launcher_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


